#!/bin/bash
sudo dpkg --remove math
remove_man(){
	echo "Removing manpage..."
	sudo rm -f /usr/share/man/man1/math.1.gz
	if [ "$?" == "0" ];then
		echo "manpage removed"
	else
		echo "fiedlde to remove the manpage!"
	fi
}
remove_math(){
	echo "removing /bin/math..."
	sudo rm -f /bin/math
	if [ "$?" == "0" ];then
	        echo "math removed"
	else
	        echo "fiedlde to remove the math!"
	fi
}
remove_man
remove_man="$?"
remove_math
remove_math="$?"
if [ "$remove_man" = "0" ] && [ "$remove_math" = "0" ];then
	echo "The Math Game Removed Sucsessfully!"
else
	echo "Fieled to uninstall math programm!"
fi
